### PR TITLE
apps:glusterfs update volume hosts info during node deletion

### LINKED ISSUE #1273: newly created volume info showing deleted node IP
### Kind of issue

> Bug

### Observed behavior
I have done node removal in heketi and created a volume, but new volume info contains the removed node IP

### Expected/desired behavior
heketi should pick up the node IP from the heketi cluster, newly created volume should have contains removed node IP

### Details on how to reproduce (minimal and precise)
1)load topology in heketi (it has 3 nodes)
2)create 4  volumes
3)add a new node to heketi
4)disable one old node in heketi
5)remove the same node
6)remove devices
7)delete the node from heketi
8)create the new volume (check vol info)
### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

### LINKED ISSUE #1274: after node delete from heketi, backup-volfile-servers in volumes contains removed node IP
### Kind of issue

 Bug

### Observed behavior
after node delete from heketi, the volumes present in the heketi is having ```backup-volfile-servers``` as removed node IP

### Expected/desired behavior
once the node is deleted  from heketi, heketi should refresh volume info as it should not point out to deleted node IP

### Details on how to reproduce (minimal and precise)
1)load topology in heketi (it has 3 nodes)
2)create 4  volumes
3)add a new node to heketi
4)disable one old node in heketi
5)remove the same node
6)remove devices
7)delete the node from heketi
8)check volume info on old volumes
### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

### PR DESCRIPTION
**Pull request by Madhu-1**
### What does this PR achieve? Why do we need it?
during the node delete in heketi, we remove the node from
heketi management, volume info such as Hosts (which may
contain the deleting node hostname). and we need to
update the backup-volfile-servers and volume mountpoint
(this also may contain the deleting node hostname)

if it's a block hosting volume, we need to
fetch all the block volumes belongs to it,
and update the hosts in those volumes, so that
next block volume creation fetches the new
hosts from the heketi cluster.

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### Does this PR fix issues?

Fixes #1274
Fixes #1273

### CODE REVIEW

File: apps/glusterfs/app_node.go [hunk 1]
```diff
@@ -320,6 +321,49 @@ func (a *App) NodeDelete(w http.ResponseWriter, r *http.Request) {
 				return err
 			}
 
+			volumes, err := ListCompleteVolumes(tx)
```
Comment (phlogistonjohn) [inline apps/glusterfs/app_node.go]: This feels like it should be it's own function, it's fairly long and conceptually independent from the surrounding code. Something like `refreshVolumeNodes(tx, clusterID)`

Comment (phlogistonjohn) [inline apps/glusterfs/app_node.go]: I think this should only iterate over the volumes in the cluster that was changed rather than all volumes.

File: apps/glusterfs/app_node.go [hunk 2]
```diff
@@ -320,6 +321,49 @@ func (a *App) NodeDelete(w http.ResponseWriter, r *http.Request) {
...
+						}
+
+						if err := blockEntry.Save(tx); err != nil {
+							logger.LogError("Save block entry for ID %s Failed with error %s", id, err.Error())
+							continue
+						}
+					}
+				}
+				//update mountpoint info
+				if err = volEntry.updateMountInfo(txdb); err != nil {
```
Comment (phlogistonjohn) [inline apps/glusterfs/app_node.go]: I don't think this function will do what we want. Based on my reading of the code this may wipe out any other options in the map other than backup-volfile-servers.

Additionally, this function has the same problem as I mentioned above about repeatedly going to the db only to get the same results over and over again in a loop.

I suggest:
* Extracting (as you've already partially done) the inner parts of `updateMountInfo` into new functions:
  * One that iterates over the nodes in the cluster and returns a list of the storage host names of those nodes. This function would be standalone and not attached to any struct.
  * Make the latter half of updateMountInfo into a helper function that takes a list of hosts and sets/updates the hosts and Options.
* Call it from updateMountInfo and before the start of the loop over the volumes.
* Now the loop over the block volumes sets .Hosts to the new list
* The loop over the volumes uses the helper function to update (& not overwrite) the mountpoint and options.

File: apps/glusterfs/app_node.go [hunk 3]
```diff
@@ -320,6 +321,49 @@ func (a *App) NodeDelete(w http.ResponseWriter, r *http.Request) {
...
+				if volEntry.Info.Block {
+					for _, id := range volEntry.Info.BlockInfo.BlockVolumes {
+
+						blockEntry, err := NewBlockVolumeEntryFromId(tx, id)
+						if err != nil {
+							logger.LogError("Get block volume entry for ID %s Failed with error %s", id, err.Error())
+							continue
+						}
+
+						if err = blockEntry.updateHosts(txdb); err != nil {
```
Comment (phlogistonjohn) [inline apps/glusterfs/app_node.go]: This strikes me as rather suboptimal. We're in a nested loop calling the same "db queries" over and over again in a transaction such that we're always going to get the same results. It strikes me as more correct to simply fetch the list of nodes for the cluster and re-use that list throughout the loop. See my comment on `updateMountInfo` for more details.

**Comment by phlogistonjohn** [comment]
ok to test

**Comment by humblec** [comment]
LGTM.
