### PR TITLE
Gorilla Context Memory leak

### LINKED ISSUE #1777: Memory leak
### Kind of issue
 Bug

### Observed behavior
heketi memory usage permanently grows

### Expected/desired behavior
memory usage is the same

### Details on how to reproduce (minimal and precise)
I have just heketi with one volume- and it is reproduces

### Information about the environment:

- Heketi version : release/8 but the MR was merged there manually to investigate the bug: https://github.com/heketi/heketi/pull/1396 
- Operating system used: container in openshift 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: it running inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): openshift-ansible

### Other useful information

Memory usage of heketi container grows this way: Снимок экрана 2020-09-07 в 21 50 35

Also pprof top after heketi was just installed:

> (pprof) top           
> Showing nodes accounting for 4.45MB, 100% of 4.45MB total
> Showing top 10 nodes out of 66
>       flat  flat%   sum%        cum   cum%
>     1.50MB 33.72% 33.72%     1.50MB 33.72%  runtime.mapassign
>     1.07MB 23.99% 57.71%     1.07MB 23.99%  compress/flate.(*compressor).init
>     0.88MB 19.80% 77.51%     1.95MB 43.79%  compress/flate.NewWriter
>     0.50MB 11.26% 88.77%     0.50MB 11.26%  reflect.unsafe_NewArray
>     0.50MB 11.23%   100%     0.50MB 11.23%  net/url.parse
>          0     0%   100%     1.95MB 43.79%  compress/flate.NewWriterDict
>          0     0%   100%     1.95MB 43.79%  compress/zlib.(*Writer).Write
>          0     0%   100%     1.95MB 43.79%  compress/zlib.(*Writer).writeHeader
>          0     0%   100%     1.95MB 43.79%  encoding/binary.Write
>          0     0%   100%     0.50MB 11.26%  encoding/json.(*decodeState).array

pprof top after 3 days:

> (pprof) top
> Showing nodes accounting for 88.02MB, 91.65% of 96.03MB total
> Showing top 10 nodes out of 119
>       flat  flat%   sum%        cum   cum%
>    30.01MB 31.25% 31.25%    32.52MB 33.87%  runtime.mapassign
>       17MB 17.70% 48.95%       17MB 17.70%  runtime.rawstringtmp
>       11MB 11.46% 60.41%       11MB 11.46%  net/http.(*Request).WithContext
>        6MB  6.25% 66.66%        6MB  6.25%  runtime.makemap
>        5MB  5.21% 71.87%        5MB  5.21%  net/url.parse
>        5MB  5.21% 77.07%        5MB  5.21%  context.WithCancel
>        4MB  4.17% 81.24%        4MB  4.17%  reflect.unsafe_New
>     3.50MB  3.64% 84.88%    34.01MB 35.41%  net/textproto.(*Reader).ReadMIMEHeader
>     3.50MB  3.64% 88.53%     3.50MB  3.64%  net/http.readTransfer
>        3MB  3.12% 91.65%        3MB  3.12%  runtime.convT2E

Heap graph: 
[pprof001.pdf](https://github.com/heketi/heketi/files/5184701/pprof001.pdf)

Example of heap trace:

> 13MB runtime.mapassign
> net/textproto.(*Reader).ReadMIMEHeader
> net/http.readRequest
> net/http.(*conn).readRequest
> net/http.(*conn).serve
> runtime.goexit
>

### PR DESCRIPTION
**Pull request by alenavorozhbieva**
### What does this PR achieve? Why do we need it?
Using gorilla/context leads to memory leaks on go version more than 1.7. https://github.com/gorilla/context.

### Does this PR fix issues?
fixes #1777 

Fixes #
In this MR I changed gorilla context to http.Request.Context()

### CODE REVIEW

File: apps/glusterfs/app_middleware.go [hunk 1]
```diff
@@ -29,7 +28,8 @@ var (
 func (a *App) Auth(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
 
 	// Value saved by the JWT middleware.
-	data := context.Get(r, "jwt")
+	ctx := r.Context()
+	data := ctx.Value("jwt")
```
Comment (iamniting) [inline apps/glusterfs/app_middleware.go:32]: This can be replaced with 

`r.Context().Value("jwt")`

**Comment by iamniting** [comment]
Hi @alenavorozhbieva Thanks for the PR. We do have some guidelines for commits. You can refer to below link for it.

https://github.com/heketi/heketi/blob/master/docs/contributing.md

pls squash commit 3 and 4 into one.

for apps files component should be apps, for middleware it should be Middleware and for test files it should be Test

**Review by iamniting — CHANGES_REQUESTED** [review]

**Comment by phlogistonjohn** [comment]
Thanks a ton for pursuing this! So far on a quick glance this looks pretty simple which is encouraging. As @iamniting mentioned we generally want the patches that make up a PR to encapsulate a single logical change, as well as work stand alone. In your case this basically means squashing them together.  If you are unsure about how to do that or uncomfortable with git, etc. please just let us know and we'll try to help out on that front.

**Comment by alenavorozhbieva** [comment]
I squashed two commits and changed the commits' messages

**Comment by phlogistonjohn** [comment]
I think that instead of "escape of" in the commit messages something like "stop" would be more grammatical, and thus clearer, english. For example the first commit would read: "middleware: stop using gorilla context".
Thanks!

**Comment by phlogistonjohn** [comment]
The changes with titles of "formatting" and "refactoring" (after the topics) should be squashed into the matching patch of the original set of three. After that I think we'll be OK on the patch structuring and we can give a proper review!

**Review by izachinyaev — COMMENTED** [review]
Looks good

**Comment by alenavorozhbieva** [comment]
Can you please check now?

**Comment by iamniting** [comment]
retest this please

**Review by phlogistonjohn — APPROVED** [review]
LGTM. Thanks so much for looking into this.

**Review by iamniting — APPROVED** [review]

**Comment by mykaul** [comment]
What prevents this from merge?

**Review by raghavendra-talur — APPROVED** [review]

**Comment by raghavendra-talur** [comment]
> What prevents this from merge?

@phlogistonjohn was waiting for my review and it slipped my mind.
